// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5KCjLPr8PRcdb7gs3_ZBEBNGbG5AGYZc',
    appId: '1:255973384963:web:ee3cd251620771c4473f36',
    messagingSenderId: '255973384963',
    projectId: 'triplife-ced4d',
    authDomain: 'triplife-ced4d.firebaseapp.com',
    storageBucket: 'triplife-ced4d.appspot.com',
    measurementId: 'G-9GQHXBEBD4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClAqryX921v2K5ZotvFEgUaalnpzonzr4',
    appId: '1:255973384963:android:bb6e7498cc6bcd21473f36',
    messagingSenderId: '255973384963',
    projectId: 'triplife-ced4d',
    storageBucket: 'triplife-ced4d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMIdEVvyg_5s3rV8DAwZUx5XrLJbnN6Jg',
    appId: '1:255973384963:ios:9f8946eeef6e30b6473f36',
    messagingSenderId: '255973384963',
    projectId: 'triplife-ced4d',
    storageBucket: 'triplife-ced4d.appspot.com',
    iosClientId: '255973384963-lhd86a015ue15klfk4ufa1u6pejjemo9.apps.googleusercontent.com',
    iosBundleId: 'com.example.tripLife',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMIdEVvyg_5s3rV8DAwZUx5XrLJbnN6Jg',
    appId: '1:255973384963:ios:9f8946eeef6e30b6473f36',
    messagingSenderId: '255973384963',
    projectId: 'triplife-ced4d',
    storageBucket: 'triplife-ced4d.appspot.com',
    iosClientId: '255973384963-lhd86a015ue15klfk4ufa1u6pejjemo9.apps.googleusercontent.com',
    iosBundleId: 'com.example.tripLife',
  );
}
